config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :img_elements
  get 'find', to: 'articles#find'
  resources :articles do
    resources :comments
  end
  resources :tags, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_one_attached :image

  has_many :comments, dependent: :destroy
  has_many :img_elements
  has_many :taggings,dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :user
  validates_presence_of :user_id

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  def self.tagged_with(name)
    Tag.find_by!(name: name).articles
  end

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article

  validates :commenter, presence: true
  validates :body, presence: true
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.paginate(:page => params[:page], :per_page => 4)
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def find
    @articles = Article.all
    @articles = @articles.select { |article| article.title.include? params[:q] }
    @articles = Article.where(id: @articles.map(&:id)).order(updated_at: :desc).paginate(:page => params[:page], :per_page => 5)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image, :all_tags, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.all
    redirect_to articles_path(@articles)
  end
end

app/controllers/img_elements_controller.rb
class ImgElementsController < ApplicationController
  article.img_elements.create
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find_by(name: params[:id])
    @articles = @tag.articles
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/image_elements_helper.rb
module ImageElementsHelper
end

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= form_with model: article do |form| %>
    <div class="form-group">
      <%= form.label :title %><br>
      <%= form.text_field :title, class: 'form-control' %>
      <% article.errors.full_messages_for(:title).each do |message| %>
        <div><%= message %></div>
     <% end %>
    </div>

    <div class="form-group">
     <%= form.label :body %><br>
      <%= form.text_area :body, class: 'form-control' %><br>
      <% article.errors.full_messages_for(:body).each do |message| %>
       <div><%= message %></div>
      <% end %>
    </div>

    <div class="form-group">
      <%= form.label :all_tags, placeholder="All tags: (separate with a comma)"%><br>
      <%= form.text_field :all_tags%>
    </div>

    <div class="form-group"><br>
      <% if article.image.attached? %>
        <%= image_tag article.image, style: "width: 200px; display: block" %>
      <% end %>

      <%= form.label :image %>
      <%= form.file_field :image, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
      <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
    </div>

    <div class="form-group">
      <%= form.label :status %><br>
      <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/find.html.erb
<div class="articles-list">
  <% @articles.select { |article| article.status == "public" }.each do |article| %>
    <div class="list-element">
      <h2 class="title-header"><a href="/articles/<%= article.id %>"><%= article.title %></a></h2>
      <h4><%= article.updated_at %></h4>
    </div>
  <% end %>
  <% if @articles.size == 0 %>
    <h2>There are no any found articles</h2>
  <% end %>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<div class="row">
  <div class="col-8">
    <% @articles.each do |article| %>
      <div class="card p-3">
        <h4><%= link_to article.title, article %></h4>
        <%= raw article.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary'}.join(' ') %>
        <p><%= truncate article.body, length: 200  %></p>
        <br><time><%= article.created_at.to_date.strftime("%d %B, %Y") %></time>
      </div>
    <% end %>
  </div>
</div>

<%= will_paginate @articles, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>Tags: <%= @article.all_tags %></p>
<p>Posted: <%= time_ago_in_words @article.created_at %> ago.</p>
<%= simple_format @article.body %>

<% if user_signed_in? %>
  <% if current_user.id == @article.user_id %>
<ul>
  <li><%= link_to "Edit", edit_article_path(@article) %></li>
  <li><%= link_to "Destroy", article_path(@article),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
    <% end %>
<% end %>

<div class="form-group"><br>
  <% if @article.image.attached? %>
    <%= image_tag @article.image, style: "width: 200px; display: block" %>
  <% end %>
</div>

<h2>Comments</h2>
<%= render @article.comments %>

<% if current_user != nil %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if user_signed_in? %>
  <% if current_user.id == @article.user_id %>
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>
  <% end %>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>

  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
<% end %>

app/views/elements/_navbar.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Fake Reddit</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", href='/articles#index', class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "New Article", new_article_path, class: 'nav-link' %>
          </li>
        <% end %>

        <form class="d-flex" action="/find" method="get">
          <input class="form-control me-2" type="search" placeholder="Search article" aria-label="Search" name="q">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogTest</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'elements/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <%= yield %>
    </div>
  </div>
</div>

</body>
</html>

app/views/tags/show.html.erb
<h1><%= @tag.name  %></h1>
<% if @tag.articles.empty? %>
  <h2>There aren`t any articles</h2>
<% else %>
  <div class="form-group">
    <div class="row">
      <div class="col-8">
        <% @articles.each do |article| %>
          <div class="card p-3">
            <h4><%= link_to article.title, article %></h4>
            <%= raw article.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: 'tag tag-primary'}.join(' ') %>
            <p><%= truncate article.body, length: 200  %></p>
            <br><time><%= article.created_at.to_date.strftime("%d %B, %Y") %></time>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>